# Generated by Django 5.1.1 on 2024-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0012_sugerencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencias',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
