# Generated by Django 5.1.1 on 2024-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0013_sugerencias_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='comentario',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
