# Generated by Django 5.1.1 on 2024-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0014_reporte_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='reporte',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
