# Generated by Django 5.1.1 on 2024-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0015_formatos_alter_reporte_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=150)),
                ('resina', models.CharField(max_length=150)),
                ('densidad_de_bulto', models.FloatField()),
                ('temperatura_secado', models.FloatField()),
                ('tiempo_secado', models.FloatField()),
                ('densidad', models.FloatField()),
            ],
        ),
    ]
