# Generated by Django 5.1.1 on 2024-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0016_resinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinas',
            name='densidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resinas',
            name='densidad_de_bulto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resinas',
            name='temperatura_secado',
            field=models.FloatField(null=True),
        ),
    ]
