# Generated by Django 5.1.1 on 2024-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0017_alter_resinas_densidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
