# Generated by Django 5.1.1 on 2024-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0018_alter_reporte_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='planta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
