# Generated by Django 5.1.1 on 2024-12-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0020_reporte_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='formato',
        ),
    ]
